/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javachallenge;

import org.junit.Assert;
import org.junit.Test;

import java.sql.Connection;
import java.util.List;

public class BookRepositoryTests {
    @Test
    public void test_getAllBooks() {
        List<Book> expected = null;
        List<Book> actual = BookRepository.getInstance().getAllBooks();
        Assert.assertEquals(expected, actual);
    }
}
