/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javachallenge;

import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class BookRepositoryTests {

    @Test
    public void test_getAllBooks_returnsSameCountAsTable() {
        int expected = 5;
        List<Book> actual = BookRepository.getInstance().getAllBooks();
        Assert.assertEquals("should return 5 for both lists", expected, actual.size());
    }




}
