/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javachallenge;

import org.junit.Assert;
import org.junit.Test;

import java.sql.Connection;

public class JdbcTests {
    @Test
    public void JdbcGetConnection() {
        Connection actual = Jdbc.getConnection();
        Assert.assertNotNull(actual);
    }

    @Test
    public void JdbcParseDbIntoBookObject() {
        Book expected = new Book();
        Book actual = Jdbc.parseIntoBook();
        Assert.assertEquals(expected.getClass(), actual.getClass());
    }

}
